"""empty message

Revision ID: 951ce2a758a7
Revises: cd1b4701d865
Create Date: 2023-11-17 18:45:44.633997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951ce2a758a7'
down_revision = 'cd1b4701d865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=8000), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module')
    # ### end Alembic commands ###
