"""empty message

Revision ID: ed2e750edf6a
Revises: 951ce2a758a7
Create Date: 2023-11-17 19:35:04.927771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2e750edf6a'
down_revision = '951ce2a758a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=8000),
               type_=sa.String(length=80000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=25050),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=25050),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('img',
               existing_type=sa.String(length=80000),
               type_=sa.VARCHAR(length=8000),
               existing_nullable=True)

    # ### end Alembic commands ###
