"""empty message

Revision ID: f01fbd3271d1
Revises: ed2e750edf6a
Create Date: 2023-11-17 22:16:14.293006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01fbd3271d1'
down_revision = 'ed2e750edf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=800), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
